// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyb-e5FfLvccpXdN2R5yUCyfH1mIfA454',
    appId: '1:433670515802:web:e251890cd661fbb2a4fc63',
    messagingSenderId: '433670515802',
    projectId: 'adamsolskab',
    authDomain: 'adamsolskab.firebaseapp.com',
    databaseURL: 'https://adamsolskab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'adamsolskab.appspot.com',
    measurementId: 'G-EK5V5GRT3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClOr2WjdaYoGsLm5s8EtWqA_ogdbM5YuI',
    appId: '1:433670515802:android:9f3fc4880123e835a4fc63',
    messagingSenderId: '433670515802',
    projectId: 'adamsolskab',
    databaseURL: 'https://adamsolskab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'adamsolskab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdJqL_O3NaFZyH9acPf-vvXty1sio6JtE',
    appId: '1:433670515802:ios:366f50b1f098e411a4fc63',
    messagingSenderId: '433670515802',
    projectId: 'adamsolskab',
    databaseURL: 'https://adamsolskab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'adamsolskab.appspot.com',
    androidClientId: '433670515802-7ghtsteraa6dcjhes1v49kppctt3jct7.apps.googleusercontent.com',
    iosClientId: '433670515802-qqchllrovm524rf56ucnnredbc2m9rsf.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.ikoladam',
  );
}
